village:
  spacing: 2
  separation: 1
  salt:
desert-pyramid:
  spacing: 2
  separation: 1
  salt:
igloo:
  spacing: 2
  separation: 1
  salt:
jungle-pyramid:
  spacing: 2
  separation: 1
  salt:
swamp-hut:
  spacing: 2
  separation: 1
  salt:
pillager-outpost:
  spacing: 2
  separation: 1
  salt:
monument:
  spacing: 2
  separation: 1
  salt:
endcity:
  spacing: 2
  separation: 1
  salt:
mansion:
  spacing: 2
  separation: 1
  salt:
ruined-portal:
  spacing: 2
  separation: 1
  salt:
shipwreck:
  spacing: 2
  separation: 1
  salt:
ocean-ruin:
  spacing: 2
  separation: 1
  salt:
bastion-remnant:
  spacing: 2
  separation: 1
  salt:
fortress:
  spacing: 2
  separation: 1
  salt:
nether-fossil:
  spacing: 2
  separation: 1
  salt:
